# Generated by Django 6.0.6 on 2026-06-18 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='email_notifications',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='telegram_notifications',
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/', verbose_name='Вложение'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Срок исполнения'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='last_status_changed_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения статуса'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='priority',
            field=models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('critical', 'Критический')], default='medium', max_length=20, verbose_name='Приоритет'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='service_type',
            field=models.CharField(choices=[('it', 'IT-поддержка'), ('hr', 'HR-сервис'), ('finance', 'Финансовый сервис'), ('legal', 'Юридический сервис'), ('office', 'Офисная инфраструктура')], max_length=20, verbose_name='Тип сервиса'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('submitted', 'Новая'), ('in_review', 'На рассмотрении'), ('approved', 'Одобрена'), ('rejected', 'Отклонена'), ('closed', 'Закрыта')], default='draft', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='items_per_page',
            field=models.PositiveIntegerField(default=10, verbose_name='Записей на странице'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='last_seen_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='requests_app.servicerequest', verbose_name='Последняя заявка'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='theme',
            field=models.CharField(choices=[('light', 'Светлая'), ('dark', 'Тёмная')], default='light', max_length=20, verbose_name='Тема интерфейса'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portal_settings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
